import os
import glob
import pandas as pd
import streamlit as st
from PIL import Image

# Streamlit Page Setup
st.set_page_config(
    page_title="Stock AI System & Portfolio Dashboard",
    page_icon="📈",
    layout="wide"
)

# File Paths
REPORTS_DIR = "reports"
FIGURES_DIR = os.path.join(REPORTS_DIR, "figures")

# --- Cached Data Loading Functions ---
@st.cache_data
def load_csv_data(file_name):
    path = os.path.join(REPORTS_DIR, file_name)
    if os.path.exists(path):
        return pd.read_csv(path)
    return None

# Sidebar Navigation
st.sidebar.title("Navigation")
page = st.sidebar.radio("Select View:", [
    "Overview & Recommendations",
    "Model Evaluation (ML vs DL)",
    "Portfolio Optimization & Backtest"
])

st.sidebar.markdown("---")
st.sidebar.info("Layer 7 Presentation: Reading cached pipeline outputs.")

# ==========================================
# PAGE 1: RECOMMENDATIONS & REBALANCING
# ==========================================
if page == "Overview & Recommendations":
    st.title("📈 Layer 6: Signal Fusion & Trade Recommendations")
    st.markdown("System recommendations generated by combining model predictions and Max-Sharpe MPT weights.")

    rec_df = load_csv_data("recommendations.csv")
    rebalance_df = load_csv_data("rebalancing_orders.csv")

    if rec_df is not None:
        st.subheader("Asset Recommendations & Signals")
        
        # Display Metric Cards for Each Ticker
        cols = st.columns(len(rec_df))
        for idx, row in rec_df.iterrows():
            with cols[idx]:
                signal = row["Recommendation Signal"]
                color = "green" if signal == "BUY" else ("red" if signal == "SELL" else "off")
                st.metric(
                    label=f"{row['Ticker']}",
                    value=f"{row['Expected Return (%)']}%",
                    delta=f"Signal: {signal}",
                    delta_color=color
                )
        
        st.markdown("---")
        st.subheader("Transparent Rationale Breakdown")
        st.dataframe(rec_df, use_container_width=True)
    else:
        st.warning("`recommendations.csv` not found in `reports/`. Run `python src/recommend.py` first.")

    if rebalance_df is not None:
        st.subheader("Portfolio Rebalancing Orders ($100,000 Portfolio Target)")
        st.dataframe(rebalance_df, use_container_width=True)

# ==========================================
# PAGE 2: MODEL EVALUATION & LOSS CURVES
# ==========================================
elif page == "Model Evaluation (ML vs DL)":
    st.title("📊 Sections 8 & 9: Model Comparison & Loss Curves")
    st.markdown("Benchmark metrics across all Machine Learning and Deep Learning models.")

    master_df = load_csv_data("master_model_comparison.csv")
    sentiment_df = load_csv_data("sentiment_experiment_results.csv")

    if master_df is not None:
        st.subheader("Master Eight-Model Comparison Table")
        st.dataframe(master_df, use_container_width=True)
    else:
        st.warning("`master_model_comparison.csv` not found. Run `python src/evaluate.py` first.")

    st.markdown("---")
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("FinBERT Sentiment Experiment Impact")
        if sentiment_df is not None:
            st.dataframe(sentiment_df, use_container_width=True)
        else:
            st.info("No sentiment experiment results found.")

    with col2:
        st.subheader("Deep Learning Loss Curves")
        curve_files = glob.glob(os.path.join(FIGURES_DIR, "*_loss_curve.png"))
        if curve_files:
            selected_curve = st.selectbox("Select Model Loss Curve:", [os.path.basename(f) for f in curve_files])
            img = Image.open(os.path.join(FIGURES_DIR, selected_curve))
            st.image(img, caption=selected_curve, use_column_width=True)
        else:
            st.info("No loss curves found in `reports/figures/`.")

# ==========================================
# PAGE 3: PORTFOLIO OPTIMIZATION & BACKTEST
# ==========================================
elif page == "Portfolio Optimization & Backtest":
    st.title("⚖️ Section 11: Modern Portfolio Theory (MPT)")
    st.markdown("Efficient Frontier optimization and strategy backtest vs equal-weight benchmark.")

    weights_df = load_csv_data("portfolio_weights.csv")

    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("Optimal Max-Sharpe Weights")
        if weights_df is not None:
            st.dataframe(weights_df, use_container_width=True)
        else:
            st.warning("`portfolio_weights.csv` not found. Run `python src/portfolio.py` first.")

    with col2:
        st.subheader("Efficient Frontier & Monte Carlo")
        ef_path = os.path.join(FIGURES_DIR, "efficient_frontier.png")
        if os.path.exists(ef_path):
            img = Image.open(ef_path)
            st.image(img, caption="Efficient Frontier Plot", use_column_width=True)
        else:
            st.info("Efficient frontier plot not found in `reports/figures/`.")